CREATE PROCEDURE [dbo].[FI_SP_AdicionarBeneficiario]
    @CPF VARCHAR(11),
    @NOME VARCHAR(50),
    @IDCLIENTE BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [dbo].[BENEFICIARIOS] (CPF, NOME, IDCLIENTE)
    VALUES (@CPF, @NOME, @IDCLIENTE);

    	SELECT SCOPE_IDENTITY()
END;